# Generated by Django 3.1 on 2020-09-01 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airforcePassWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('birthDate', models.DateField()),
                ('cpf', models.TextField(max_length=11, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
