# Generated by Django 3.1 on 2020-09-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airforcePassWeb', '0002_dependent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperties',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
