# Generated by Django 3.1.1 on 2020-09-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airforcePassWeb', '0006_auto_20200902_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
