# Generated by Django 3.1.1 on 2020-09-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airforcePassWeb', '0007_auto_20200902_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperties',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
