# Generated by Django 3.1.1 on 2020-09-03 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airforcePassWeb', '0010_auto_20200903_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperties',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userproperties', to='auth.user'),
        ),
    ]
